title: "Ochieng Tony Blair"
email: tonyblairochieng7@gmail.com
description: >- 
  My AI, Robotics & Engineering Portfolio.
baseurl: "" # leave empty for GitHub Pages
url: "https://tblair24.github.io"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

author:
  name   : "Ochieng Tony Blair"
  avatar : "/assets/images/profile.jpg"
  bio    : "Aspiring AI and Robotics Researcher"

markdown: kramdown
highlighter: rouge

# Add navigation links
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/
