title: "Ochieng Tony Blair"
description: "My AI, Robotics & Engineering Portfolio"
url: "https://tblair24.github.io"
baseurl: "" # Important: leave blank unless using a subfolder

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Ochieng Tony Blair"
  avatar : "/assets/images/profile.jpg"
  bio    : "Aspiring AI and Robotics Researcher"

markdown: kramdown
highlighter: rouge

# Navigation example
nav:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/
